title: "Koki Maeda"
description: "Doctoral Student · Tokyo Institute of Technology"
url: "https://Silviase.github.io"
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "Koki Maeda"
  email: "koki.maeda@nlp.c.titech.ac.jp"
  links:
    - label: "GitHub"
      url: "https://github.com/Silviase"
    - label: "LinkedIn"
      url: "https://linkedin.com/in/silviase"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"

nav:
  - title: "Home"
    url: "/"
  - title: "CV"
    url: "/cv/"
